### ISSUE TITLE
After a while it won't work 

### ISSUE THREAD

**Issue by micheld93** [prebm/SonosRemote#2]
Hi, 

first, I want to tell you I really like your project. Unfortunately, there is a problem I can't solve. After a while I can't control my Sonos speaker any more. It's happening after inactivity (I'm at work and coming back and then it won't work.). There are 2 easy solutions:

1. Control from Sonos speaker or app
2. log in via ssh on pi without doing anything else

I think, (2) tells us that there is a stand by mode. I tried these steps (excuse me that it's in german. The commands are the same, so I hope it is understandable):

https://www.elektronik-kompendium.de/sites/raspberry-pi/1912231.htm (it's for WLAN Stand-by)

https://www.elektronik-kompendium.de/sites/raspberry-pi/2107011.htm (for HDMI Monitors)

This is what the status says:
![bildschirmfoto 2017-01-26 um 18 22 54](https://cloud.githubusercontent.com/assets/7882686/22342381/7c04c328-e3f4-11e6-9e7e-95d24455e5e1.png)

I would really appreciate a solution or a tip to solve it. Thanks...

**Comment by prebm** [comment]
> I tried these steps ...

From your text it is not clear if it solved your problem. Did it solve your problem?

I can remember I've had similar issues . I will have to research a bit to see if I made some changes, that I haven't commited (though I can't think of any reason why I shouldn' have).

I have my Pi connected via Ethernet and for a long time I didn't have any issues with lost connectivity. I pressume you have your PI connected via a USB WIFI dongle. Can you try to connect your Pi via Ethernet and not WIFI? If the problems stop, we will definitely know it is the WIFI dongle. And if not we will dig deeper.

**Comment by micheld93** [comment]
Hi, 

with "these steps" I mean the things written in the links. And no, unfortunately, the are not solving anything. 

I have a RasPi 3, so there is no WiFi Dongle. Ethernet can be tried at the weekend. I will get in touch again after testing ethernet connections.

**Comment by prebm** [comment]
Closing because it seems to work. I can reopen if you have issues again.

**Comment by micheld93** [comment]
Sorry for the delay. I have to admit that I totally forgot to write/answer. I'm currently busy working. 

I still have the problem and it remains with ethernet/LAN connection.
